version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:15"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      pip-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
